stages:
  - build
  - test
  - docker

build:
  stage: build
  image: node:lts
  before_script:
    - cd client/
  script: 
    - npm install
    - npm run build

test:
  stage: test
  image: node:lts
  before_script:
    - cd client/
  script:
    - npm install
    - npm test

docker-build:
  when: manual
  tags:
    - hdm-runner-yumatch
  stage: docker
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" ./client
    - docker push "$CI_REGISTRY_IMAGE${tag}"
