package io.foodtinder.dataservice.constants;

public enum MealArea {
    AMERICAN, BRITISH, CANADIAN, CHINESE, CROATIAN, DUTCH, EGYPTIAN, FRENCH, GREEK, INDIAN, IRISH, ITALIAN, JAMAICAN,
    KENYAN, JAPANESE, MALAYSIAN, MEXICAN, MOROCCAN, POLISH, PORTUGUESE, RUSSIAN, SPANISH, THAI, TUNISIAN, TURKISH,
    VIETNAMESE
}