import {
  CUISINES,
  DIETS,
  INTOLERANCES,
  TYPES,
} from "../../utils/user/User.types";

export interface UserSettingsProps {}

export const dietsArr: DIETS[] = [
  DIETS.VEGAN,
  DIETS.VEGETARIAN,
  DIETS.GLUTENFREE,
  DIETS.NOPORK,
];

export const intolerancesArr: INTOLERANCES[] = [
  INTOLERANCES.PEANUT,
  INTOLERANCES.FISH,
  INTOLERANCES.ONION,
  INTOLERANCES.GARLIC,
  INTOLERANCES.TOMATOE,
];

export const cuisinesArr: CUISINES[] = [
  CUISINES.ITALIAN,
  CUISINES.ASIAN,
  CUISINES.GREEK,
  CUISINES.SOUTHAMERICAN,
  CUISINES.AFRICAN,
  CUISINES.SPANISH,
  CUISINES.FRENCH,
];

export const typesArr: TYPES[] = [
  TYPES.CAFE,
  TYPES.COLD,
  TYPES.WARM,
  TYPES.DESSERT,
];
